image:
  name: "openjdk:11.0.11-9-jdk"

stages:
  - build
  - release

build:
  stage: build
  script:
    - ./mvnw clean package -DskipTests=true
    - ./mvnw verify
    - ./deploy-snapshot.sh

release:
  stage: release
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+.*/'
  script:
    - ./deploy-release.sh
